name: EYE SEE HUE JINIUS
favicon: null
layout_spectrum: 0.9268469859380275
typography_spectrum: 0.09110321151092649
title: IMAJIN
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8368272162042558
  lightness: 0.28311257902532816
  saturation: 0.5310875212308019
  rhythmicContrast: 0.5431276368908584
purpose: []
